2022-07-19 11:35:44,174 INFO    MainThread:17732 [wandb_setup.py:_flush():76] Configure stats pid to 17732
2022-07-19 11:35:44,174 INFO    MainThread:17732 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Nicor\.config\wandb\settings
2022-07-19 11:35:44,175 INFO    MainThread:17732 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Nicor\OneDrive\Documents\KolkowitzLab\Ellipse fitting\Learners\wandb\settings
2022-07-19 11:35:44,175 INFO    MainThread:17732 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-19 11:35:44,175 INFO    MainThread:17732 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-07-19 11:35:44,176 INFO    MainThread:17732 [wandb_init.py:_log_setup():461] Logging user logs to C:\Users\Nicor\OneDrive\Documents\KolkowitzLab\Ellipse fitting\Learners\wandb\run-20220719_113544-1btai7py\logs\debug.log
2022-07-19 11:35:44,176 INFO    MainThread:17732 [wandb_init.py:_log_setup():462] Logging internal logs to C:\Users\Nicor\OneDrive\Documents\KolkowitzLab\Ellipse fitting\Learners\wandb\run-20220719_113544-1btai7py\logs\debug-internal.log
2022-07-19 11:35:44,177 INFO    MainThread:17732 [wandb_init.py:init():495] calling init triggers
2022-07-19 11:35:44,177 INFO    MainThread:17732 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-07-19 11:35:44,177 INFO    MainThread:17732 [wandb_init.py:init():548] starting backend
2022-07-19 11:35:44,177 INFO    MainThread:17732 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-07-19 11:35:44,183 INFO    MainThread:17732 [backend.py:ensure_launched():217] starting backend process...
2022-07-19 11:35:44,237 ERROR   MainThread:17732 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "C:\Users\Nicor\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 1043, in init
    run = wi.init()
  File "C:\Users\Nicor\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 556, in init
    backend.ensure_launched()
  File "C:\Users\Nicor\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\backend\backend.py", line 220, in ensure_launched
    self.wandb_process.start()
  File "C:\Users\Nicor\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Nicor\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Nicor\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Nicor\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Nicor\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
